##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
## (C) Copyright 2018-2019 Modeling Value Group B.V. (http://modelingvalue.org)                                        ~
##                                                                                                                     ~
## Licensed under the GNU Lesser General Public License v3.0 (the 'License'). You may not use this file except in      ~
## compliance with the License. You may obtain a copy of the License at: https://choosealicense.com/licenses/lgpl-3.0  ~
## Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on ~
## an 'AS IS' BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the  ~
## specific language governing permissions and limitations under the License.                                          ~
##                                                                                                                     ~
## Maintainers:                                                                                                        ~
##     Wim Bast, Tom Brus, Ronald Krijgsheld                                                                           ~
## Contributors:                                                                                                       ~
##     Arjan Kok, Carel Bast                                                                                           ~
##~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: 'upload-jetbrains-plugin-action'
description: 'upload a plugin to the JetBrains marketplace'
author: 'Tom Brus'

inputs:
  file:
    description: 'the zip file with the plugin to upload'
    required: true
  hubToken:
    description: 'the JetBrains hub token to authorize an update'
    required: true
  pluginId:
    description: 'a number identifying the plugin'
    required: true
  channel:
    description: 'a word that indicates the channel (defaults to branch dependent)'
    required: false
  trace:
    description: 'set this to "true" if you would like bash-tracing'
    required: false
    default: "false"

runs:
  using: 'composite'
  steps:
    - shell: bash
      id: main
      run: |
        set -euo pipefail
        [[ "${{inputs.trace}}" == "true" ]] && set -x

        if [[ "${{inputs.hubToken}}" == "" ]]; then
          echo "::error::hubToken can not be empty, create a token at https://hub.jetbrains.com"
          exit 85
        fi
        if [[ "${{inputs.pluginId}}" == "" ]]; then
          echo "::error::pluginId can not be empty, do a manual upload first at https://plugins.jetbrains.com/plugin/add"
          exit 86
        fi
        if [[ ! "${{inputs.file}}" == *.zip && ! "${{inputs.file}}" == *.jar ]]; then
          echo "::error::plugins should be packaged in zip or jar files"
          exit 87
        fi

        channel="${{inputs.channel}}"
        if [[ "$channel" == "" ]]; then
          branch="${GITHUB_REF#refs/heads/}"
          if [[ "$branch" == "master" ]]; then
            channel="stable"
          elif [[ "$branch" == "develop" ]]; then
            channel="eap"
          else
            echo "::info::skipping publish of jetbrains plugin because branch ($branch) is not master or develop"
          fi
        fi

        if [[ "$channel" != "" ]]; then
          echo "::info::publishing plugin ${{inputs.pluginId}} on $channel channel"
          curl \
            -v \
            -i \
            --header "Authorization: Bearer ${{inputs.hubToken}}" \
            -F "pluginId=${{inputs.pluginId}}" \
            -F  "channel=$channel" \
            -F     "file=@${{inputs.file}}" \
            "https://plugins.jetbrains.com/plugin/uploadPlugin"
      
          echo
          echo "::info::find your updated plugin at https://plugins.jetbrains.com/plugin/${{inputs.pluginId}}"
        fi